### PR TITLE
(#71) initials of integration for SnoopPrecompile

### PR DESCRIPTION
**Pull request by jbytecode**
This is the initial adaptation of SnoopPrecompile.

### CODE REVIEW

**Comment by jbytecode** [comment]
It is interesting that the tests were not passed.

**Comment by jmejia8** [comment]
Did work on your Julia distribution?

**Comment by jbytecode** [comment]
yes, of course, in 1.9.rc1

**Comment by jbytecode** [comment]
```julia
Test Summary:   | Pass  Total     Time
Multi objective |  118    118  1m14.8s
Test Summary: | Pass  Total  Time
Combinatorial |    4      4  9.2s
Test Summary:                          | Pass  Total  Time
DecisionMaking: Compromise Programming |    6      6  1.9s
Test Summary:       | Pass  Total  Time
DecisionMaking: ROI |    4      4  1.0s
Test Summary:         | Pass  Total   Time
DecisionMaking: JMcDM |   34     34  14.2s
Test Summary:     | Pass  Total  Time
Initial Solutions |   87     87  3.1s
     Testing Metaheuristics tests passed 

(Metaheuristics) pkg> 
```

**Comment by jmejia8** [comment]
Maybe, It is time to upgrade Julia (>= 1.8) in the test environment 

https://github.com/jmejia8/Metaheuristics.jl/blob/b7c27384a2d3bc3c7c3be5dd34efdead45728dbe/.github/workflows/CI.yml#L16

due to

https://discourse.julialang.org/t/ann-new-package-snoopprecompile/84778

**Comment by jbytecode** [comment]
Can we test it by upgrading the version in only github workflow?

**Comment by jbytecode** [comment]
Last time I used v1.5.2 was Sep or Oct, 2020

**Comment by jbytecode** [comment]
even v1.8 is not enough to get tests passed :(

**Comment by jbytecode** [comment]
nightly builds seem to work..

**Comment by jmejia8** [comment]
I see.. BTW, the errors comes due to

https://github.com/jmejia8/Metaheuristics.jl/blob/b7c27384a2d3bc3c7c3be5dd34efdead45728dbe/src/TestProblems/TestProblems.jl#L78

Calling `eval` at that level is breaking the pre-compilation stage.

**Comment by jbytecode** [comment]
yes, the problem may not be about versioning.

**Comment by jmejia8** [comment]
We need to refactor this function

https://github.com/jmejia8/Metaheuristics.jl/blob/b7c27384a2d3bc3c7c3be5dd34efdead45728dbe/src/TestProblems/TestProblems.jl#L76

before proceed.

**Comment by jmejia8** [comment]
The original PR is now passing the tests. Thank you!

**Pull request merged**
